# Prediction using a multiple linear regression model


In [47]:
import numpy as np
import pandas as pd

# Import and split the dataset

In [56]:
dataset = pd.read_csv('train.csv')
dataset.head()
X = dataset.iloc[:, [0, 2, 6, 7]].values
y = dataset.iloc[:, 1].values


# Have a summary of the dataset

In [57]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


# Look for null values in the dataset


In [58]:
dataset.isnull().sum() # Here we can see that we have null values on many Age information from Passengers, there fore to base the prediction in the age would output a biased result

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

# Splitting the dataset into the training and test set

In [59]:
testDataset = pd.read_csv('test.csv')
testDataset.isnull().sum()
X_test = testDataset.iloc[:, [0, 1, 5, 6]].values
y_test = testDataset.iloc[:, 1].values
print(X_test)

[[ 892    3    0    0]
 [ 893    3    1    0]
 [ 894    2    0    0]
 ...
 [1307    3    0    0]
 [1308    3    0    0]
 [1309    3    1    1]]


# Training the multiple linear regression model on the training set

In [60]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X, y)

LinearRegression()

#Predictin the test set results

In [86]:
rawPredictions = regressor.predict(X_test)
predictions = []
for x in rawPredictions:
  if x > 0.45: predictions.append(1)
  else: predictions.append(0)

deaths = predictions.count(0)
output = pd.DataFrame({'PassengerId': X_test[:, 0], 'Survived': predictions})
output.to_csv('submission5.csv', index=False)
print('Submission saved with deaths/total', deaths, '/', len(X_test))


Submission saved with deaths/total 291 / 418
